### ISSUE TITLE
Mineral Sizer

### ISSUE THREAD

**Issue by whatthefugde** [al132/ATM-Rockhounding#1]
Every time it runs it crashes the server. 

Stacktrace:
    at al132.atmrockhounding.tile.TileMineralSizer.canOutput(TileMineralSizer.java:93)
    at al132.atmrockhounding.tile.TileMineralSizer.canProcess(TileMineralSizer.java:150)
    at al132.atmrockhounding.tile.TileMineralSizer.func_73660_a(TileMineralSizer.java:135)

-- Block entity being ticked --
Details:
    Name: MineralSizer // al132.atmrockhounding.tile.TileMineralSizer
    Block type: ID #857 (tile.atmrockhounding:mineralSizer // al132.atmrockhounding.blocks.MineralSizer)
Everyone on the server who has a mineral sizer has been experiencing it
We are running 1.0.23

**Comment by al132** [comment]
Is the server running spongeforge by chance? I haven't heard about this issue from anyone except your server.
